#!/bin/bash
#build file for Unix system
compileDir=$(cd `dirname $0` && /bin/pwd)
# Go inside the ProActive directory
cd "$compileDir/.."
trap "echo $args | grep -c junit > /dev/null && dev/scripts/killTests" SIGINT SIGTERM
ANT_HOME="$compileDir" "$JAVA_HOME"/bin/java  -Dant.home="$compileDir" -Dant.library.dir="$compileDir/lib" -Xmx512000000 -classpath "$compileDir"/lib/ant-launcher.jar org.apache.tools.ant.launch.Launcher -buildfile  "$compileDir"/build.xml $args
# Execute run.sh script
scriptsDir=$(cd "$compileDir/../scripts" && /bin/pwd)
"$scriptsDir/run.sh"

